# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2.0'

# Framework
gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'

# Server
gem 'puma', '~> 6.0'

# Database
gem 'sequel', '~> 5.0'
gem 'sqlite3', '~> 1.6'

# JSON
gem 'json', '~> 2.6'

# Development & Test
group :development, :test do
  gem 'rake', '~> 13.0'
  gem 'rubocop', '~> 1.50', require: false
end

group :test do
  gem 'rack-test', '~> 2.0'
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22', require: false
end
